Gimbal: Added rc channel control readme
ArduPilot/ardupilot_gazebo pull request #104
Opened 2024-06-30 15:30 UTC by snktshrma

In reference to the [PR](https://github.com/ArduPilot/ardupilot_gazebo/pull/102) by @srmainwaring. Updated readme to setup and control gimbal over ground control.

2024-06-30 15:45 UTC, srmainwaring requested changes

2024-06-30 15:45 UTC, srmainwaring commented on README.md
> +`Open QGC > Application Settings > Video Settings > Select UDP h.264 Video Stream & use port 5600`
Add a screen shot of the QGC settings panel?

2024-06-30 15:45 UTC, srmainwaring commented on README.md
> +View the streamed camera frames in OGC:
typo: OCG -> QCG. Make a hyperlink to the relevant QCG help page.

2024-06-30 15:45 UTC, srmainwaring commented on config/gazebo-iris-gimbal.parm
> +SERVO11_FUNCTION  6
Add blank line at end.

2024-06-30 15:45 UTC, srmainwaring commented on README.md
> +### 4. Using Gimbal
maybe: Using the 3d gimbal

2024-06-30 15:45 UTC, srmainwaring commented on README.md
> +To control gimbal using RC channels,
Suggestion: The Iris model is equipped with a 3d gimbal and camera that can be controlled directly in MAVProxy using the RC overrides.

2024-06-30 15:47 UTC, srmainwaring commented
Thanks for the PR @snktshrma. Looks good. Have suggested a few changes. A screenshots of the QGC settings page might help clarify the setup, but not essential.

2024-06-30 16:17 UTC, snktshrma commented
Hi @srmainwaring! I have resolved the requested changes and added a screenshot of QGC settings page!

2024-06-30 23:27 UTC, rmackay9 commented
@snktshrma, Thanks for this.  The QGC image isn't appear for me and the url looks a bit suspicious (https://private-user-images.githubusercontent.com/74557164/344478908-f55242f3-cff8-4f81-befd-da68e4df73c6.png).

2024-07-01 03:42 UTC, snktshrma commented
Hi @rmackay9 sir! I have updated the image! Hopefully it's visible now

2024-09-10 19:32 UTC, srmainwaring commented
Adding resized image here so it can be referenced from as an asset in the main repo.

![qgc_video_settings](https://github.com/user-attachments/assets/61fa4c2a-37e2-47cf-abcf-9f110d9c2015)

2024-09-10 20:34 UTC, srmainwaring approved these changes
Looks good thanks @snktshrma. I've rebased to bring the parameters up to date with `main` and referenced the QGC image from this repo rather than your fork.

2024-09-11 09:40 UTC, merged