IGN -> GZ
ArduPilot/ardupilot_gazebo pull request #27
Opened 2022-06-23 18:32 UTC by ahcorde

Build on top of this other PR https://github.com/ArduPilot/ardupilot_gazebo/pull/26

2022-06-23 22:48 UTC, srmainwaring commented
@khancyr yes that's right - Garden only.

@ahcorde I've been making similar changes for another Gazebo plugin (my marine ocean one), wondering if it is worth waiting until the Gazebo Garden interface is finalised before merging this change as I've been through a few iterations catching up as the namespace migration progresses; on the other hand the namespace changes may be breaking for Garden.

2022-06-24 07:57 UTC, ahcorde commented
we are still migrating `ign -> gz`, 

I openned this PR just in case someone want to try this with Garden. I will try to keep it updated

2022-06-27 10:58 UTC, srmainwaring commented
@ahcorde is the reset functionality required by the ign -> gz migration or is it optional? If it's optional we should split that into a separate PR.

2022-07-28 11:50 UTC, ahcorde commented
Hi @srmainwaring @khancyr,

this is ready for a review

2022-07-28 12:59 UTC, srmainwaring requested changes
Hi @ahcorde, thanks for `ign` -> `gz` migration changes. I've made similar changes to my local branch and they seem to be in line.

The one feature I have not checked is the reset interface - so I'll need to run your branch to check that. Otherwise it's just a few minor changes here and there - mainly using the library short form in the plugins and switching the message ostream to the `gz` version.

2022-07-28 12:59 UTC, srmainwaring commented on README.md
> +The project is composed of an Gazebo plugin to connect to ArduPilot SITL (Software In The Loop) and some example models and worlds.
minor gram. chg.  *an Gazebo* to *a Gazebo*

2022-07-28 12:59 UTC, srmainwaring commented on README.md
> +Follow the instructions for a [binary install of ignition fortress](https://ignitionrobotics.org/docs/garden/install) and verify that ignition gazebo is running correctly.
Link is to garden, comment is for fortress. Suggest change comment to garden as well.

2022-07-28 12:59 UTC, srmainwaring commented on models/iris_with_standoffs/model.sdf
> +    <plugin filename="libgz-sim-joint-state-publisher-system.so"
We can drop the `lib` prefix and `.so` suffix on the library names, so

`libgz-sim-joint-state-publisher-system.so` to `gz-sim-joint-state-publisher-system`, etc.

2022-07-28 12:59 UTC, srmainwaring commented on src/ArduPilotPlugin.cc
> +        ignwarn << "Failed to do position control on joint " << i <<
Change `ignwarn` to `gzwarn` and similarly for `ignmsg`?

2022-07-28 12:59 UTC, srmainwaring commented on src/ArduPilotPlugin.cc
>          << this->dataPtr->fcu_address << ":" << this->dataPtr->fcu_port_out << "\n"
Change `igndbg` to `gzdbg`.

2022-08-16 19:26 UTC, srmainwaring approved these changes
@ahcorde this LGTM, thanks!

Have tested `iris_arducopter_runway.world` on latest pull of gz-sim (d90fab) against ArduPilot master on macOS Monterey Version 12.5, Xcode  13.2.1 and it's working well.

2022-08-16 19:27 UTC, merged